### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by eugene-galkine** [SAP/iot-services-sdk#1]
I requested the top 50000 measures and from the DeviceService and it resulted in a crash:

```
Traceback (most recent call last):
  File "C:/Users/EGalkine/Documents/iot/sap-iot.py", line 6, in <module>
    response = device_service.get_measures(device_id="196", top="50000")
  File "C:\Users\EGalkine\Documents\venv\lib\site-packages\iot_services_sdk\device.py", line 248, in get_measures
    response = self.request_core(method='GET', service=service, query=query, accept_json=True)
  File "C:\Users\EGalkine\Documents\venv\lib\site-packages\iot_services_sdk\iot_service.py", line 122, in request_core
    raise DeviceManagementAPIException(json.loads(err.response.text)['message'])
  File "C:\Python3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by steinroe** [comment]
Hi,

thank you for reaching out. 

Which version do you have installed? You can check it with `pip show iot_services_sdk`.

If it is not v1.2, would you mind updating? I think the error you got was fixed with 1.2.

Best
Philipp

**Comment by eugene-galkine** [comment]
The version is I have is 1.2

Thank you,
Eugene

**Comment by steinroe** [comment]
Alright, could you show me the code snippet you use? For me, the following works just fine:
```
from iot_services_sdk import DeviceService

INSTANCE = <instance>
USER = <user>
PASSWORD = <pw>

device_service = DeviceService(instance = INSTANCE,
                                user = USER,
                                password = PASSWORD)

get_measures_response = device_service.get_measures('2f0d6b3d-1148-4a41-ae83-6bf5a0c796a0', top='5000')

print(get_measures_response.get_result())
```

**Comment by eugene-galkine** [comment]
```python
from iot_services_sdk import DeviceService

device_service = DeviceService(instance='INSTANCE', user='USER', password='PASSWORD')

response = device_service.get_measures(device_id='196', top='5000')
print(response.get_result())
```

This works, but this does not:

```python
from iot_services_sdk import DeviceService

device_service = DeviceService(instance='INSTANCE', user='USER', password='PASSWORD')

response = device_service.get_measures(device_id='196', top='50000')
print(response.get_result())
```

**Comment by steinroe** [comment]
I can the exact same code snippet but do not receive the same error. However, I just uploaded a quick fix which expects the `json.decoder.JSONDecodeError` and instead raises the original error without parsing. Could you please upgrade to v1.3 and try again?

**Comment by steinroe** [comment]
Should be fixed now - can you check again after another update?

**Comment by eugene-galkine** [comment]
Got this error now:

```
Traceback (most recent call last):
  File "C:\Users\EGalkine\Documents\venv\lib\site-packages\iot\iot_service.py", line 123, in request_core
    raise DeviceManagementAPIException(json.loads(err.response.text)['message'])
  File "C:\Python3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/EGalkine/Documents/iot/sap-iot.py", line 6, in <module>
    response = device_service.get_measures(device_id="196", top="50000")
  File "C:\Users\EGalkine\Documents\venv\lib\site-packages\iot_services_sdk\device.py", line 248, in get_measures
    response = self.request_core(method='GET', service=service, query=query, accept_json=True)
  File "C:\Users\EGalkine\Documents\venv\lib\site-packages\iot_services_sdk\iot_service.py", line 125, in request_core
    raise DeviceManagementAPIException(err)
iot_services_sdk.iot_service.DeviceManagementAPIException: 504 Server Error: Request Timeout for url: https://REDACTED/devices/196/measures?top=50000
```

**Comment by steinroe** [comment]
Your instance url is wrong. It has to be the form myinstance.eu10.cp.iot.sap.

What is the url to access the IoT Service UI? It should be something like https://myinstance.eu10.cp.iot.sap
Just remove the https:// - that is your instance url.

**Comment by eugene-galkine** [comment]
it does, I just redacted it for the post

**Comment by steinroe** [comment]
Can you tell me the IoT Services version you are using?

**Comment by eugene-galkine** [comment]
v1 I believe

**Comment by steinroe** [comment]
You can find it after logging in to your IoT Service Cockpit. If you press the i button in the top right corner, a dialog will appear which lists the version number. Could you please check that? 

The error is saying that the connection can't be established. This is most likely an error caused by a wrong url or a wrong path, which could be the case if your IoT Services version it too old.

**Comment by eugene-galkine** [comment]
The version is 4.41.0

**Comment by steinroe** [comment]
Alright, I know where the problem is... IoT Services changed their API so that each call has to be made tenant-specific. I will update that, but won't get to it until end of next week.
